### ISSUE TITLE
no compile on debian-derivative: cannot stat 'linux-4.9.92-dappersec180530-15.tar.gz'

### ISSUE THREAD

**Issue by miroR** [dapperlinux/dapper-secure-kernel-patchset-stable#4]
I made the script (beginner-oriented):
https://github.com/miroR/grsec-dapper-compile/
( it's just a simple conversion from https://github.com/miroR/grsec-dev1-compile/ .)
And, purposefully to eliminate my LOCALVERSION modification, I made the no-localv branch:

https://github.com/miroR/grsec-dapper-compile/blob/no-localv/grsec-dapper-compile.sh

(it was worse with the main branch script). But I still get:

```
  INSTALL debian/headertmp/usr/include/sound/ (15 files)
  INSTALL debian/headertmp/usr/include/video/ (3 files)
  INSTALL debian/headertmp/usr/include/xen/ (4 files)
  INSTALL debian/headertmp/usr/include/uapi/ (0 file)
  INSTALL debian/headertmp/usr/include/asm/ (65 files)
dpkg-deb: building package 'linux-headers-4.9.92-dappersec180530-15' in '../linux-headers-4.9.92-dappersec180530-15_4.9.92-dappersec180530-15-1_amd64.deb'.
dpkg-deb: building package 'linux-libc-dev' in '../linux-libc-dev_4.9.92-dappersec180530-15-1_amd64.deb'.
dpkg-deb: building package 'linux-image-4.9.92-dappersec180530-15' in '../linux-image-4.9.92-dappersec180530-15_4.9.92-dappersec180530-15-1_amd64.deb'.
mv: cannot stat 'linux-4.9.92-dappersec180530-15.tar.gz': No such file or directory
make[1]: *** [scripts/package/Makefile:93: deb-pkg] Error 1
make: *** [Makefile:1352: deb-pkg] Error 2
```

It's probably an issue to ask about also on Debian/Devuan ML ...

**Comment by miroR** [comment]
To show how it is worse with master branch (with LOCALVERSION modification) of the script, here is the log:

```
  INSTALL debian/headertmp/usr/include/sound/ (15 files)
  INSTALL debian/headertmp/usr/include/video/ (3 files)
  INSTALL debian/headertmp/usr/include/xen/ (4 files)
  INSTALL debian/headertmp/usr/include/uapi/ (0 file)
  INSTALL debian/headertmp/usr/include/asm/ (65 files)
dpkg-deb: building package 'linux-headers-4.9.92-dappersec180530-16' in '../linux-headers-4.9.92-dappersec180530-16_4.9.92-dappersec180530-16-1_amd64.deb'.
dpkg-deb: building package 'linux-libc-dev' in '../linux-libc-dev_4.9.92-dappersec180530-16-1_amd64.deb'.
dpkg-deb: building package 'linux-image-4.9.92-dappersec180530-16' in '../linux-image-4.9.92-dappersec180530-16_4.9.92-dappersec180530-16-1_amd64.deb'.
mv: cannot stat 'linux-4.9.92-dappersec180530-16.tar.gz': No such file or directory
make[1]: *** [scripts/package/Makefile:93: deb-pkg] Error 1
make: *** [Makefile:1352: deb-pkg] Error 2
```

See the uncomfortable long name there:
**linux-headers-4.9.92-dappersec180530-16_4.9.92-dappersec180530-16-1_amd64.deb**

Should be an indication, but it will take somebody with more knowledge than me to figure out how to sort this... Will try and ask about this... where? Devuan ML? If I manage... Or Debian ML otherwise... 
(I run a Devuan system, the non-systemd fork, but kernels in Devuan are just, to my knowledge, taken from Debian without modifications.)

**Comment by miroR** [comment]
And just a clarification: I haven't had any issues like this with grsecunoff kernels (which I have compiled a number of, in recent months, and uploaded for others to use, so this must be a dapper-secure-kernel issue, to my best understanding (not an expert).

**Comment by msr50** [comment]
That looks like a complicated script. Do you have all the compile output for the kernel? The kernel might not have built properly, and left you without a kernel to package.

Are you using GCC8? The patchset still has some compile errors for now, and will be fixed in a later release.

Have you updated your config? A number of new config options have been added since 4.9.74, such as CONFIG_BPF_JIT_ALWAYS_ON  or CONFIG_CRYPTO_JITTERENTROPY to name a few. You might have problems if you don't keep your config up to date.

I'll have a look at your script when I get some time, which will probably be the weekend. I'll have to install a Debian based distro in a VM, so I'll have a look at Devuan. 

I'm a Fedora guy myself, and you can see how I make my rpm files here: https://github.com/dapperlinux/dapper-secure-kernel-stable
Its useful even if you see how I make my config:
https://github.com/dapperlinux/dapper-secure-kernel-stable/blob/master/config-x86_64-generic
https://github.com/dapperlinux/dapper-secure-kernel-stable/blob/master/config-local

**Comment by miroR** [comment]
> That looks like a complicated script. 

No, it's just downloading kernel, your patch, my config, checking sigs, and compiling the way kernels in Debian are compiled.

> Do you have all the compile output for the kernel?

Yest I do! I always try to keep those... But how do I sanitize those... I'm shy of posting all secrets about my kernel open... If you want, I can encrypt it to your key and send it to you.
Also if anyone knowledgeable, @HacKurx or someone else want to help, I can send them too...

> The kernel might not have built properly, and left you without a kernel to package.

May be... Haven't yet check on Devuan/Debian MLs to get more help on this.

**Comment by HacKurx** [comment]
@miroR 
> mv: cannot stat 'linux-4.9.92-dappersec180530-16.tar.gz': No such file or directory

Compares the name of the tar.gz file generated at the beginning of the compilation with the one expected at the end.
You must have a problem in your script, at worst edit the mv command in the file  "scripts/package/builddeb".

**Comment by miroR** [comment]
> >   mv: cannot stat 'linux-4.9.92-dappersec180530-16.tar.gz': No such file or directory

> Compares the name of the tar.gz file generated at the beginning of the compilation with the one expected at the end.
> You must have a problem in your script, at worst edit the mv command in the file "scripts/package/builddeb".

There wasn't any '*tar.gz' to be found when I search after the compilation ended with that error.

And I've compiled dozens of kernels with that script (well, with the grsec-dev1-compile.sh and previously with grsec-deb-compile.sh) for years. Never yet such an error have I seen...

I have, however, located what you are indicating for editing:
```$ tail -11 scripts/package/builddeb
        mv ${sourcename}.tar.gz ../${sourcename}_${version}.orig.tar.gz
        tar caf ../${sourcename}_${packageversion}.debian.tar.gz debian/{copyright,rules,changelog,control}
        dpkg-source -cdebian/control -ldebian/changelog --format="3.0 (custom)" --target-format="3.0 (quilt)" \
                -b / ../${sourcename}_${version}.orig.tar.gz  ../${sourcename}_${packageversion}.debian.tar.gz
        mv ${sourcename}_${packageversion}*dsc ..
        dpkg-genchanges > ../${sourcename}_${packageversion}_${debarch}.changes
else
        dpkg-genchanges -b > ../${sourcename}_${packageversion}_${debarch}.changes
fi

exit 0
```

Trying to figure out how to edit it (if that is the way to go/try). Thanks!

**Comment by miroR** [comment]
@msr50 @HacKurx  I think I'm close to the cause of the failure.
But first, I forgot to answer @msr50's question. I'm compiling with:
``` $ gcc --version
gcc (Debian 7.2.0-19) 7.2.0
```
Now, there's this error, which some of you guys will surely find where to locate the code to fix. First two lines show where it happens (right after https://github.com/dapperlinux/dapper-secure-kernel-patchset-stable/issues/3#issuecomment-393370213 ):

```crypto/Kconfig:1613:    symbol CRYPTO_ANSI_CPRNG depends on CRYPTO
warning: (INET_ESP && INET6_ESP) selects CRYPTO_ECHAINIV which has unmet direct dependencies (CRYPTO)
#
# configuration written to .config
#
  CHK     include/config/kernel.release
  UPD     include/config/kernel.release
make clean
  TAR     linux-4.9.92-dappersec.tar.gz
/bin/sh: 1: +tar: not found
make KBUILD_SRC=
```
See that:
```/bin/sh: 1: +tar: not found
```
Of course it can't tar nothing, not with the +tar command, but where is that in the code?...

Found it, I think!

```
/path-to-linux-4.9.92$ grep -r '+tar\>' ./
./debian/hdrtmp/usr/src/linux-headers-4.9.92-dappersec180530-15/scripts/package/Makefile:+tar --owner=root --group=root -cz $(RCS_TAR_IGNORE) -f $(2).tar.gz \
./scripts/package/Makefile:+tar --owner=root --group=root -cz $(RCS_TAR_IGNORE) -f $(2).tar.gz \
```
Yep! Only these two lines... I guess you guys will know how o fix that!

**Comment by miroR** [comment]
ERRATA

See that:
``` 
/bin/sh: 1: +tar: not found
```

**Comment by miroR** [comment]
So I just fixed the Makefile:
```
sed 's/+tar/tar/'
```
and the linux-4.9.92-dappersec.tar.gz is there now... I'm compiling with one core one (-j1). Will take time...

**Comment by miroR** [comment]
Running 4.9.92-dappersec on another system. But that's kernel tailor-made for my system, for only my system, no modules loading at all, all functionalities compiled in (so much safer).
Next, try and build it with functionalities compiled separately in modules, so it works on mosts systems, and offer it to other folks awaiting this solution. 
( At:
http://forums.debian.net/viewtopic.php?f=16&t=108616
or at
https://dev1galaxy.org/viewtopic.php?id=596
)
Which patch got that typo, I didn't look into, but I'm sure @msr50 will easily fix that. So I'm leaving it to you, Matthew, to close this issue.

**Comment by msr50** [comment]
Oops. Sorry @miroR for that, it was my fault. Thanks for finding the problem! I Indeed left a stray + sign on patches/a_scripts_package_Makefile.patch 

I work on a patch by patch basis, and frequently modify individual patches to resolve merge conflicts, and I sometimes copy and paste old patches to a new tree to resolve conflicts, and sometimes I forget to remove the + sign, and end up with a ++ in the patch which patches to +. 

I went and searched all of my patches for any more mistakes, with the command
grep -Rin "^++" | grep -v "b"
This looks for ++ characters at the start of lines and then ignores any with "b" in the line, which is how patch manages what file to patch. 
I found no more, so that was the only case.

Its fixed in https://github.com/dapperlinux/dapper-secure-kernel-patchset-stable/commit/480f38b3add59343451f781b079a7973a64abc19

And it will be present from when I next release 4.9.93+ which will likely when I have some time tomorrow to sit down and work on the patchset. 

Thanks for pointing it out!

**Comment by miroR** [comment]
Looks good, your kernel, being prepared for some kind of public upload (in a repo or, as for years I offered for grsec orig, in non-advance style --see the links in my previous post--).

Just the issue https://github.com/dapperlinux/dapper-secure-kernel-patchset-stable/issues/3 , I think, is visible to be solved.

And retpoline support is missing in comparison with the last grsecunoff (minipli's). I hope @HacKurx can help out there.

Thank you! While spectre and meltdown defences surely are still missing, all/most of the other good features of grsec look perfectly available. I have Role Based Access Control very much properly deployed, and it appears to me, all is great that way...

**Comment by miroR** [comment]
The:
https://www.croatiafidelis.hr/gnu/deb/linux-deb-grsec-current/
now points to:
https://www.croatiafidelis.hr/gnu/deb/linux-4.9.92-dappersec180601-06/
That is the kernel package for Debian/Devuan that _may_ be worth trying out, bearing in mind the caveats of Dapper Linux patchset:
https://dapperlinux.com/
I.e. no meltdown protection, no spectre protection, currently no retpoline.
I'll try and make a post about it on both Debian and Devuan forums, next.

**Comment by miroR** [comment]
I added at the and of the previous post:

I'll try and make a post about it on both Debian and Devuan forums, next. And turn the download location into 
a  README as usual (if more time, I'd make a repo).

**Comment by miroR** [comment]
Here:
https://dev1galaxy.org/viewtopic.php?pid=9637#p9637
and:
http://forums.debian.net/viewtopic.php?f=16&t=108616&p=674315#p674315
